### ISSUE TITLE
EncodingError in v3.0.4

### ISSUE THREAD

**Issue by staltz** [flumedb/flumeview-level#11]
**Description:** when using flumeview-level 3.0.4 (which in turn uses level v3), we see an encoding error for the `META` message.

For context, the only change between the versions is https://github.com/flumedb/flumeview-level/compare/c6ac9b9426f10bb5e77ef224d6025b0e3ca0ffd5...master :

- flumeview-level 3.0.1 uses level 1.7.0
- flumeview-level 3.0.4 uses level 3.0.1

Note, if level had breaking changes, so should flumeview-level

**Code to reproduce:**

```js
var pull = require('pull-stream'); // 3.6.2
var ssbKeys = require('ssb-keys'); // 7.0.16
var FlumeViewLevel = require('flumeview-level'); // 3.0.4
var CreateTestSbot = require('scuttle-testbot'); // 1.1.5

var lucyKeys = ssbKeys.generate();
var myTestSbot = CreateTestSbot({ name: 'bug-test-db', keys: lucyKeys });
var lucy = myTestSbot.createFeed(lucyKeys);

lucy.add({ type: 'post', text: 'Thread root' }, () => {});

var index = myTestSbot._flumeUse(
  'bug-test-index',
  FlumeViewLevel(1, (msg, seq) => [
    [msg.value.timestamp, msg.key],
  ]),
);

setTimeout(() => { 
  pull(
    index.read({old: true, live: false}),
    pull.collect((err, all) => {
      console.error(err); // THIS WILL GENERATE THE REPORT BELOW
      console.log(all); // THIS WILL GENERATE THE REPORT BELOW
    })
  )
}, 400);
```

Node: v8.11.1 on GNU/Linux 4.15.0-20-generic x86_64
npm: v5.6.0

**Actual behavior once run in `node`:**

```
EncodingError: no decoder for:"\u0000"
    at /home/alice/folder/ssb-threads/node_modules/encoding-down/index.js:112:17
    at /home/alice/folder/ssb-threads/node_modules/leveldown/node_modules/abstract-leveldown/abstract-iterator.js:29:14
    at /home/alice/folder/ssb-threads/node_modules/leveldown/iterator.js:43:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[]
```

**Expected behavior once run in `node`:**

This is actually what I get when running the snippet above changing flumeview-level to be 3.0.1:

```
null
[ { key: 
     [ 1526480530232,
       '%+XWmq90L5Ilo7CGsB3jrfW/fhAMawU/86HVBXjciozM=.sha256' ],
    seq: 0,
    value: 
     { key: '%+XWmq90L5Ilo7CGsB3jrfW/fhAMawU/86HVBXjciozM=.sha256',
       value: [Object],
       timestamp: 1526480530233 } } ]
```

**Comment by staltz** [comment]
Okay, further investigation led me to realize that the snippet works with `flumeview-level@3.0.4` plus `encoding-down@3` but fails with `flumeview-level@3.0.4` plus `encoding-down@4`.

**Comment by staltz** [comment]
Wow, that's awesome you found that. Would take me much longer.

**Comment by dominictarr** [comment]
reinstall should fix this, make sure you have encoding-down@4
