### ISSUE TITLE
How do we choose `max` for pull-write?

### ISSUE THREAD

**Issue by christianbundy** [flumedb/flumeview-level#15]
I'm sure that different batch sizes are best for different machines, but on my machine the `max` value of 128 is ~33% faster than the current batch size of 512 (at least in benchmarks). As a side-note, I've noticed that when `max` is set to `n` then the batch is actually being written after `n / 2` items are added to the list (maybe I'm testing incorrectly?). 

On the other hand, I'm wondering whether some sort of hill-climbing algorithm could be implemented to find the optimal batch size over time. 

Here are my benchmark results with different sizes, it's worth noting that I'm using an in-memory flumelog because with flumelog-offset I only see batch sizes of ~12.

## 64

```
name, ops, opts/second, seconds
append, 50000, 141643.059490085, 0.353
ordered_para, 50000, 83612.04013377927, 0.598
random_para, 50000, 94876.66034155597, 0.527
ordered_series, 50000, 93109.86964618249, 0.537
random_series, 50000, 91743.11926605504, 0.545
```

## 96

```
name, ops, opts/second, seconds
append, 50000, 148367.9525222552, 0.337
ordered_para, 50000, 86805.55555555556, 0.576
random_para, 50000, 96525.09652509652, 0.518
ordered_series, 50000, 93808.63039399624, 0.533
random_series, 50000, 73206.44216691068, 0.683
```

## 128

```
name, ops, opts/second, seconds
append, 50000, 155763.2398753894, 0.321
ordered_para, 50000, 87565.67425569177, 0.571
random_para, 50000, 95238.09523809524, 0.525
ordered_series, 50000, 94517.95841209829, 0.529
random_series, 50000, 94696.9696969697, 0.528
```

## 192

```
name, ops, opts/second, seconds
append, 50000, 126903.55329949239, 0.394
ordered_para, 50000, 83194.6755407654, 0.601
random_para, 50000, 96339.11368015414, 0.519
ordered_series, 50000, 89605.73476702507, 0.558
random_series, 50000, 94696.9696969697, 0.528
```

## 256

```
name, ops, opts/second, seconds
append, 50000, 127551.02040816325, 0.392
ordered_para, 50000, 62972.292191435765, 0.794
random_para, 50000, 89605.73476702507, 0.558
ordered_series, 50000, 92764.37847866419, 0.539
random_series, 50000, 96153.84615384616, 0.52
```

## 512 

```
name, ops, opts/second, seconds
append, 50000, 114942.52873563218, 0.435
ordered_para, 50000, 62344.139650872814, 0.802
random_para, 50000, 92081.03130755064, 0.543
ordered_series, 50000, 93283.58208955223, 0.536
random_series, 50000, 98039.2156862745, 0.51
```

## 1024

```
name, ops, opts/second, seconds
append, 50000, 100000, 0.5
ordered_para, 50000, 82236.84210526316, 0.608
random_para, 50000, 73637.70250368188, 0.679
ordered_series, 50000, 39904.22984836393, 1.253
random_series, 50000, 74738.41554559043, 0.669
```

## 2048

```
name, ops, opts/second, seconds
append, 50000, 55066.07929515418, 0.908
ordered_para, 50000, 87108.01393728223, 0.574
random_para, 50000, 96525.09652509652, 0.518
ordered_series, 50000, 94517.95841209829, 0.529
random_series, 50000, 93984.96240601504, 0.532
```

**Comment by dominictarr** [comment]
> On the other hand, I'm wondering whether some sort of hill-climbing algorithm could be implemented to find the optimal batch size over time.

yes this would be awesome! one complication is that it would be easy to do when running the benchmark, but most of the time in practice the writes are very sporadic. Then suddenly they come as a big burst.

This is also likely hardware dependant.

hang on, this is only in-memory flumelog? what do you get for flumelog-offset?
probably it never hits the max. If I recall, it writes again if the write finishes and there is stuff to be written.

**Comment by christianbundy** [comment]
Yeah, it only goes up to about 12 items per write with flumelog-offset. I used an in-memory flumelog because I think the pain point is how fast the view can go when the log is way ahead.

**Comment by dominictarr** [comment]
@christianbundy can you elaborate on that a bit? you want view building to go faster?

**Comment by christianbundy** [comment]
Sorry, I was describing the behavior in response to:

> hang on, this is only in-memory flumelog? what do you get for flumelog-offset?

When using flumelog-offset I never hit `max` because flumeview-offset is about 12 times faster than flumeview-level. Instead, I've been benchmarking with an in-memory flumelog which is fast enough that we can consistently hit `max`, which is closer to real-world usage when we hit a big burst of messages and the log gets ahead of the views. 

One super simple heuristic I thought of (would be a very breaking change):

- Record the time each batch takes as `time`
- Record the fastest batch time as `fastest`
- If `time < fastest`, increase `max` by one

My intuition is that we'd have logarithmic growth toward the fastest value, maybe a bit higher, but I'm concerned that the timer functionality might slow it down. Anyway, I'll benchmark it and see if I can come up with something -- please let me know if you have any ideas, I know you've thought about this stuff a bunch.

**Comment by dominictarr** [comment]
> which is closer to real-world usage when we hit a big burst of messages and the log gets ahead of the views.

hey what about when rebuilding an index? that wouldn't be blocked by writing the log at all. how does it do if you write flumelog-offset fully, _then_ build the view.

**Comment by dominictarr** [comment]
on your huristic:

record time each batch takes, remember fastest batch, if time < fastest, increase max by one.

"increase max by one" one what? one item? would it be better to increase by a percentage?

I can see a problem with the algorithm you give, as it is, lets say, there is an "sweetspot" that gives maximum speed. below that it's slower, over that it's slower. If you always increase if time < fastest, you could overshoot, the sweetspot, and then just continue increasing max, until it gets very very large.

I think that could be fixed if it was `size/time`. I think we could test this by constructing a test that modeled a sweetspot, and then testing the algorithms ability to find that. of course, I suspect the sweetspot could move, as say, more memory is in use etc.

**Comment by dominictarr** [comment]
also, other variations on this:
* https://github.com/dominictarr/async-single/
* https://github.com/dominictarr/async-write

async write has an interesting property that it tries to keep the buffer full. it fills the buffer (up to a timer) then writes a batch. (instead of writing as soon as it has something)

**Comment by dominictarr** [comment]
prehaps we could benchmark all of these?

**Comment by christianbundy** [comment]
I'd love to. I'll try to make some time for it next week.

**Comment by christianbundy** [comment]
Didn't end up having time for this, I may loop back in the future but I'm deprioritizing it for now.
