### ISSUE TITLE
incrementing index version throws error

### ISSUE THREAD

**Issue by mmckegg** [flumedb/flumeview-level#2]
This is because the `Level.destroy` on https://github.com/flumedb/flumeview-level/blob/master/index.js#L37 must be passed a `string` location rather than the db instance.

I tried doing this, but then the create fails because for some reason the old database is not being closed.

@dominictarr any ideas how to fix?

**Comment by mmckegg** [comment]
Also noticed that decrementing the version number does not cause indexes to be regenerated. Tt should, otherwise if you go back to an old version, things could get very screwy indeed.

**Comment by dominictarr** [comment]
agree. if it's different it should rm -rf and rebuild. oh this should be an easy fix.

**Comment by dominictarr** [comment]
this should be fixed in flumeview-level@2.0.2

**Comment by mmckegg** [comment]
That's what I was using. Still has issues.
